# Site settings
## Change the values as needed.
title: Seyed Mohamad Moghadas
email: s.m.moghadas2012@gmail.com
description: "This is Moghadas's personnal website"
keywords: "Moghadas, python, django, docker"
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
url: "" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
paginate_path: "page:num"
# Build settings
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
links:
  twitter: mmoghadas
  email: s.m.moghadas2012@gmail.com
  github: https://github.com/moghadas76
exclude:
  - bower_components
  - README.md
full_name: Moghadas

##set this to enable disqus commenting
disqus: bitwiser

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in
